import Link from "next/link";
import Head from "next/head";
import React, { Fragment } from "react";
import SectionContainer from "../layout-units/SectionContainer";
import classes from "./Account.module.css";
import { useRouter } from "next/router";

const ProfileTop = () => {
  const router = useRouter();
  let currentDate = new Date();
  // let userTimeZone = currentDate.getTimezoneOffset() / 60; // return timezone in minutes, divide by 60 for hours
  // const timeElapsed = currentDate.now();
  // const now = new Date(timeElapsed);
  let currentFormatDate = currentDate.toLocaleString();
  // console.log(currentDate.toLocaleString());
  // console.log(currentDate.toTimeString());
  // console.log(currentDate.toString());
  // console.log(currentDate);
  // console.log(currentDate.getDay());
  // console.log(currentDate.getDate());
  // console.log(currentDate.getMonth());
  // console.log(currentDate.getFullYear());
  // console.log(currentDate.getTime());
  // console.log(userTimeZone);

  const accountNav = [
    { pageTitle: "Main", link: "/account" },
    { pageTitle: "Appointments", link: "/account/appointments" },
    { pageTitle: "Lineage", link: "/account/lineage" },
    { pageTitle: "DNA", link: "/account/DNA" },
    // { pageTitle: "Meals", link: "/account/meals" },
    { pageTitle: "Settings", link: "/account/settings" },
  ];

  return (
    <Fragment>
      <Head>
        <title>Your profile at HealthRecords webapp</title>
        <meta
          name="description"
          content="Generated by Your profile at HealthRecords webapp"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionContainer>
        <h1>Welcome to your profile</h1>
      </SectionContainer>
      <SectionContainer>
        <nav className={`section_container ${classes.nav_account}`}>
          <ul className={`${classes.nav_accountUl}`}>
            {accountNav.map((path) => (
              <Link href={path.link}>
                <li
                  className={`flex_center ${classes.navLink} 
                ${router.route === path.link && classes.navLink_active}`}
                >
                  <span class="material-symbols-outlined">genetics</span>
                  {path.pageTitle}
                </li>
              </Link>
            ))}
          </ul>
        </nav>
      </SectionContainer>
    </Fragment>
  );
};

export default ProfileTop;
