import Link from "next/link";
import Head from "next/head";
import React, { Fragment } from "react";
import SectionContainer from "../layout-units/SectionContainer";
import classes from "./Account.module.css";
import { useRouter } from "next/router";

const ProfileTop = () => {
  const router = useRouter();
  let currentDate = new Date();
  // let userTimeZone = currentDate.getTimezoneOffset() / 60; // return timezone in minutes, divide by 60 for hours
  // const timeElapsed = currentDate.now();
  // const now = new Date(timeElapsed);
  let currentFormatDate = currentDate.toLocaleString();
  // console.log(currentDate.toLocaleString());
  // console.log(currentDate.toTimeString());
  // console.log(currentDate.toString());
  // console.log(currentDate);
  // console.log(currentDate.getDay());
  // console.log(currentDate.getDate());
  // console.log(currentDate.getMonth());
  // console.log(currentDate.getFullYear());
  // console.log(currentDate.getTime());
  // console.log(userTimeZone);
  const accountRoute = "/account";
  const lineageRoute = "/account/lineage";
  const DNARoute = "/account/DNA";
  const appointmentsRoute = "/account/appointments";
  const dietRoute = "/account/diet";
  const settingsRoute = "/account/settings";

  return (
    <Fragment>
      <Head>
        <title>Your profile at HealthRecords webapp</title>
        <meta
          name="description"
          content="Generated by Your profile at HealthRecords webapp"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionContainer>
        <h1>Welcome to your profile</h1>
      </SectionContainer>
      <SectionContainer>
        <nav className={`section_container ${classes.nav_account}`}>
          <ul>
            <Link href={accountRoute}>
              <li
                className={`showOnPc ${classes.navLink} 
                ${router.route === accountRoute && classes.navLink_active}`}
              >
                Main
              </li>
            </Link>
            <Link href={lineageRoute}>
              <li
                className={`showOnPc  ${classes.navLink}
                ${router.route === lineageRoute && classes.navLink_active}`}
              >
                Lineage
              </li>
            </Link>
            <Link href={DNARoute}>
              <li
                className={`showOnPc  ${classes.navLink}
               ${router.route === DNARoute && classes.navLink_active}`}
              >
                DNA
              </li>
            </Link>
            <Link href={appointmentsRoute}>
              <li
                className={`showOnPc  ${classes.navLink}
               ${router.route === appointmentsRoute && classes.navLink_active}`}
              >
                Appointments
              </li>
            </Link>
            <Link href={dietRoute}>
              <li
                className={`showOnPc  ${classes.navLink}
               ${router.route === dietRoute && classes.navLink_active}`}
              >
                Diet
              </li>
            </Link>
            <Link href={settingsRoute}>
              <li
                className={`showOnPc  ${classes.navLink}
               ${router.route === settingsRoute && classes.navLink_active}`}
              >
                Settings
              </li>
            </Link>
          </ul>
        </nav>
      </SectionContainer>
    </Fragment>
  );
};

export default ProfileTop;
