import Head from "next/head";
import React, { Fragment, useState } from "react";
import { formatDate } from "../../helpers/general-helper";

import FilterYearMonth from "../../components/layout-units/FilterYearMonth";
import SectionContainer from "../../components/layout-units/SectionContainer";
import PublicationsCard from "../../components/publications/PublicationsCard";
import PublicationsList from "../../components/publications/PublicationsList";

import classes from "../../components/publications/Articles.module.css";

import {
  getFeaturedArticles,
  getUserStories,
} from "../../helpers/firebaseData-helper";

export async function getStaticProps(context) {
  //  featuredProductID identifier on file name
  const articles = await getFeaturedArticles();
  const stories = await getUserStories();
  return {
    props: { articles: articles, stories: stories },
    revalidate: 30000, // featuredProduct info changes reupdated every 500 minutes
  };
  // this  connects to the main function props
}

const PublicationsListPage = ({ articles, stories }) => {
  const [showPublications, setShowPublications] = useState(0);

  const allArticlesCards = articles.map((article) => (
    <PublicationsCard
      id={article.id}
      title={article.title}
      date={article.date}
      text={article.text}
      image={article.image}
      photo={article.photo}
      author={article.author}
    />
  ));

  const allStoriesCards = stories.map((story) => (
    <PublicationsCard
      id={story.id}
      title={story.title}
      date={story.date}
      text={story.text}
      photo={story.photo}
    />
  ));

  // test;
  // let filteredArticles = articles
  //   .map((art) => {
  //     // console.log(formatDate(art.date));
  //     const year = +art.date.toString().slice(0, 4);
  //     const month = +art.date.toString().substring(4, 6);
  //     const key = art.id;
  //     // console.log(year, month);
  //     return { year, month, ...art, key };
  //   })
  //   .filter((date) => {
  //     // console.log(date);
  //     return date.year === 2021 && date.month === 10;
  //   });
  // console.log(filteredArticles);
  // // classes

  return (
    <Fragment>
      <Head>
        <title>Health Publications at your Medical Records Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Find amazing articles written by our specialists and interesting stories
        from our users
      </h1>

      <FilterYearMonth />

      <SectionContainer>
        <nav className={` ${classes.publications_nav} `}>
          <ul className={`flex_center ${classes.pub_navUL} `}>
            <li
              className={` ${classes.pub_navUL_li} ${
                showPublications === 0 && classes.activeLi
              }`}
              onClick={() => {
                setShowPublications(0);
              }}
            >
              All
            </li>
            <li
              className={`${classes.pub_navUL_li} ${
                showPublications === 1 && classes.activeLi
              }`}
              onClick={() => {
                setShowPublications(1);
              }}
            >
              Articles
            </li>
            <li
              className={`${classes.pub_navUL_li} ${
                showPublications === 2 && classes.activeLi
              }`}
              onClick={() => {
                setShowPublications(2);
              }}
            >
              Stories
            </li>
          </ul>
        </nav>
      </SectionContainer>

      <PublicationsList>
        {showPublications === 0 && allArticlesCards}
        {showPublications === 0 && allStoriesCards}

        {showPublications === 1 && allArticlesCards}

        {showPublications === 2 && allStoriesCards}
      </PublicationsList>
    </Fragment>
  );
};

export default PublicationsListPage;
