import Head from "next/head";
import React, { Fragment } from "react";
import FacilitiesList from "../../components/consult/FacilitiesList";
import FilterConsult from "../../components/consult/FilterConsult";
import ProfessionalsList from "../../components/consult/ProfessionalsList";
import SectionContainer from "../../components/layout-units/SectionContainer";
import {
  getFacilities,
  getProfessionals,
} from "../../helpers/firebaseData-helper";

export async function getStaticProps() {
  const professionalsData = await getProfessionals();
  const facilitiesData = await getFacilities();
  return {
    props: {
      professionalsData: professionalsData,
      facilitiesData: facilitiesData,
    },
  };
}
const Consult = (props) => {
  const { professionalsData, facilitiesData } = props;

  return (
    <Fragment>
      <Head>
        <title>Health Publications at your Medical Records Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionContainer>
        <h1>Find your professional!</h1>
        <p>Below you will find our registered professionals and facilities</p>
        <FilterConsult />
      </SectionContainer>
      {facilitiesData.map((facility) => (
        <FacilitiesList facility={facility} />
      ))}
      {professionalsData.map((professional) => (
        <ProfessionalsList professional={professional} />
      ))}
    </Fragment>
  );
};

export default Consult;
