import Head from "next/head";
import React, { Fragment } from "react";
import BusinessCalendar from "../../components/consult/BusinessCalendar";
import FilterConsult from "../../components/consult/FilterConsult";
import SectionContainer from "../../components/layout-units/SectionContainer";

const Centers = () => {
  return (
    <Fragment>
      <Head>
        <title>Health Publications at your Medical Records Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionContainer>
        <h1>Find your treatment!</h1>
        <FilterConsult />
      </SectionContainer>
      <SectionContainer>
        <BusinessCalendar />
      </SectionContainer>
    </Fragment>
  );
};

export default Centers;
