import Head from "next/head";
import React, { Fragment } from "react";
import SectionTop from "../../components/layout/SectionTop";
import {
  getFacilities,
  getProfessionals,
} from "../../helpers/firebaseData-helper";
import SpecialistsCard from "../../components/consult/SpecialistsCard"

export async function getStaticProps() {
  const professionalsData = await getProfessionals();
  const facilitiesData = await getFacilities();
  return {
    props: {
      professionalsData: professionalsData,
      facilitiesData: facilitiesData,
    },
  };
}
const Consult = (props) => {
  const { professionalsData, facilitiesData } = props;

  return (
    <Fragment>
      <Head>
        <title>Health Publications at your Medical Records Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionTop consultPage={true} />
      {facilitiesData.map((facility) => (
        <SpecialistsCard facility={facility} />
      ))}
      {professionalsData.map((professional) => (
        <SpecialistsCard facility={professional} />
      ))}
    </Fragment>
  );
};

export default Consult;
