import { Fragment } from "react";
import { useSession } from "next-auth/react";

import Head from "next/head";
import SectionFeaturedArticles from "../components/home/SectionFeaturedArticles";
import SectionTop from "../components/home/SectionTop";
import SectionTopIn from "../components/home/SectionTopIn";
import SectionStories from "../components/home/SectionStories";

export default function HomePage() {
  // const { data: session, status } = useSession();

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SectionTop>
        <SectionTopIn />
      </SectionTop>
      <SectionFeaturedArticles />
      <SectionStories />
      
    </Fragment>
  );
}
