import { Fragment } from "react";

import Head from "next/head";
import SectionFeaturedArticles from "../components/home/SectionFeaturedArticles";
import SectionTop from "../components/home/SectionTop";
import SectionStories from "../components/home/SectionStories";

import {
  getFeaturedArticles,
  getUserStories,
} from "../helpers/firebaseData-helper";

export async function getStaticProps() {
  const featuredArticles = await getFeaturedArticles();
  const userStories = await getUserStories();
  return {
    props: {
      featuredArticles: featuredArticles,
      userStories: userStories,
    },
  };
}
export default function HomePage(props) {
  const { featuredArticles, userStories } = props;
  console.log(props);
  // console.log(featuredArticles);
  console.log(userStories.length);
  // const { data: session, status } = useSession();

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SectionTop />
      <SectionFeaturedArticles featuredArticles={featuredArticles} />
      <SectionStories userStories={userStories} />
    </Fragment>
  );
}
